#!/usr/bin/env python3
"""
Auto-generate MEMORY.md from frontmatter in all memory files.

Reads every .md file in the memory directory, extracts YAML frontmatter
(name, description, type), and regenerates MEMORY.md as a clean index
grouped by type.

Usage:
    python3 generate-memory-index.py                    # Preview to stdout
    python3 generate-memory-index.py --write            # Overwrite MEMORY.md
    python3 generate-memory-index.py --write --sort alpha  # Sort alphabetically within groups
"""

import argparse
import re
from pathlib import Path
from collections import defaultdict

MEMORY_DIR = Path.home() / ".claude/projects/-Users-ShawCole/memory"
INDEX_FILE = MEMORY_DIR / "MEMORY.md"

TYPE_ORDER = ["feedback", "user", "project", "reference"]
TYPE_LABELS = {
    "feedback": "Critical Rules & Feedback",
    "user": "User Profile",
    "project": "Projects",
    "reference": "References & People",
}


def extract_frontmatter(filepath: Path) -> dict | None:
    """Extract YAML frontmatter from a markdown file."""
    text = filepath.read_text(errors="replace")
    if not text.startswith("---"):
        return None

    end = text.find("---", 3)
    if end == -1:
        return None

    block = text[3:end].strip()
    result = {}
    for line in block.split("\n"):
        if ":" in line:
            key, val = line.split(":", 1)
            result[key.strip()] = val.strip()
    return result if result.get("name") and result.get("type") else None


def generate_index(sort_mode: str = "natural") -> str:
    """Generate the MEMORY.md content from all frontmatter."""
    entries = defaultdict(list)
    no_frontmatter = []

    for f in sorted(MEMORY_DIR.glob("*.md")):
        if f.name == "MEMORY.md":
            continue

        fm = extract_frontmatter(f)
        if fm:
            entries[fm["type"]].append({
                "name": fm["name"],
                "description": fm.get("description", ""),
                "file": f.name,
            })
        else:
            no_frontmatter.append(f.name)

    # Also check subdirectories
    for subdir in MEMORY_DIR.iterdir():
        if subdir.is_dir() and not subdir.name.startswith("."):
            for f in subdir.glob("*.md"):
                fm = extract_frontmatter(f)
                rel = f"{subdir.name}/{f.name}"
                if fm:
                    entries[fm["type"]].append({
                        "name": fm["name"],
                        "description": fm.get("description", ""),
                        "file": rel,
                    })

    lines = [
        "---",
        "name: Memory Index",
        "description: Auto-generated index of all memory files grouped by type",
        "type: user",
        "---",
        "",
        "# Memory Index",
        "<!-- Auto-generated by generate-memory-index.py. Do not edit manually. -->",
        "",
    ]

    for mem_type in TYPE_ORDER:
        items = entries.get(mem_type, [])
        if not items:
            continue

        if sort_mode == "alpha":
            items.sort(key=lambda x: x["name"].lower())

        label = TYPE_LABELS.get(mem_type, mem_type.title())
        lines.append(f"## {label}")
        for item in items:
            desc = f" — {item['description']}" if item["description"] else ""
            lines.append(f"- [{item['name']}]({item['file']}){desc}")
        lines.append("")

    if no_frontmatter:
        lines.append("## Unindexed (missing frontmatter)")
        for f in sorted(no_frontmatter):
            lines.append(f"- {f}")
        lines.append("")

    # Stats
    total = sum(len(v) for v in entries.values())
    lines.append(f"<!-- {total} indexed files, {len(no_frontmatter)} unindexed -->")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="Overwrite MEMORY.md")
    parser.add_argument("--sort", default="natural", choices=["natural", "alpha"])
    args = parser.parse_args()

    content = generate_index(args.sort)

    if args.write:
        INDEX_FILE.write_text(content)
        lines = content.count("\n")
        print(f"Wrote {INDEX_FILE} ({lines} lines)")
    else:
        print(content)


if __name__ == "__main__":
    main()
